export const LABELS = {
  appName: "법무 문서 DB",
  dashboard: "대시보드",
  documents: "문서 목록",
  search: "검색",
  archive: "아카이브",
  settings: "설정",
  categories: "카테고리",
  tags: "태그",
  notes: "메모",
  sync: "동기화",
  syncStart: "동기화 시작",
  syncStatus: "동기화 상태",
  lastSynced: "마지막 동기화",
  totalDocuments: "전체 문서",
  recentDocuments: "최근 문서",
  recentNotes: "최근 메모",
  addNote: "메모 추가",
  editNote: "메모 수정",
  deleteNote: "메모 삭제",
  pinNote: "메모 고정",
  searchPlaceholder: "문서 제목, 내용, 태그로 검색...",
  noResults: "검색 결과가 없습니다",
  filter: "필터",
  sortBy: "정렬",
  viewTable: "테이블 보기",
  viewCard: "카드 보기",
  allCategories: "전체 카테고리",
  status: {
    active: "활성",
    archived: "보관",
    deleted: "삭제됨",
  },
  confidentiality: {
    public: "공개",
    internal: "사내",
    confidential: "기밀",
  },
  fileType: "파일 유형",
  fileSize: "파일 크기",
  documentDate: "문서 일자",
  createdAt: "등록일",
  openInSharePoint: "SharePoint에서 열기",
  preview: "미리보기",
} as const;
